FROM node:20.12.0-alpine3.19

WORKDIR /app/user-app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install --legacy-peer-deps

# Can you add a script to the global package.json that does this? ✅
RUN npm run db:generate

# Can you filter the build down to just one app? ✅
RUN npm run dev:user

CMD ["npm", "run", "start-user-app"]