name: Build and Deploy to DockerHub

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push image
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smart-wallet:latest

      - name: Verify pushed image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/smart-wallet:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/smart-wallet:latest
            docker stop smart-wallet || true
            docker rm smart-wallet || true
            docker run -d --name smart-wallet -p 3005:3000 ${{ secrets.DOCKER_USERNAME }}/smart-wallet:latest
